### ISSUE TITLE
Real-World Cases for Networked Covert Channels

### ISSUE THREAD

**Issue by iute** [cdpxe/Network-Covert-Channels-A-University-level-Course#8]
Hello Professor, I am a student and I would like to know if there are any real cases about network covert channels, if so can you inform, thank you very much!

**Comment by lucacav** [comment]
https://github.com/lucacav/steg-in-the-wild

**Comment by cdpxe** [comment]
Thanks for posting this lust @lucacav. IMHO, this list grow into a major reference for stegomalware.

@iute: There are also some research papers on the matter, which are mentioned in the course material (and @lucacav is co-author of two of them, e.g., [https://arxiv.org/pdf/1801.00694](https://arxiv.org/pdf/1801.00694)) and we have one even more comprehensive stegomalware list under review that I will post once published, probably in 3-4 months. So, yes, there are plenty of cases where network covert channels are used in real-world malware.

**Comment by cdpxe** [comment]
Closed the cases as "not planned" by mistake. The issue was solved by referring to above-mentioned comprehensive stegomalware paper(s) and referring to the paper(s) in the latest version of the online class.
